# -*- coding: utf-8 -*-
"""wine_recommendation_nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZrtHlDBBkWtE1wRJA78iyMS9r0wQqU1

# **Finding Best Bottle of Wine with Natural Language Processing Tool**

## Objectives

 - extract information from wine dataset
 - use Hugging Face Transformer model to create embeddings
 - create a search function and visual search explorer to select wines
"""

# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
# !mamba install -qy pandas==1.3.4 numpy==1.21.4 seaborn==0.9.0 matplotlib==3.5.0 scikit-learn==0.20.1
# Note: If your environment doesn't support "!mamba install", use "!pip install"

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
import nmslib
from sklearn.manifold import TSNE

df = pd.read_csv("C:\\Users\\Sanman\\Downloads\\winemag-data-130k-v2.csv")
print("Dataset preview:")
print(df.head())
print("Interpretation: The dataset contains wine reviews, including country, description, points, and price.")

print("\nOriginal Dataset Shape:", df.shape)
print("Interpretation: The dataset initially contains 129,971 wine reviews and 14 columns.")

"""
## Data Wrangling
"""

df = df.drop_duplicates('description')
print("\nShape after dropping duplicate descriptions:", df.shape)

print("\nNull values by column:")
print(df.isnull().sum())
print("Interpretation: There are some missing values, particularly in 'price', 'region_1', and 'region_2'.")

df = df.dropna(subset=['price'])
print("\nShape after dropping rows with null prices:", df.shape)

country = df.set_index("country")

Italy = country.loc[["Italy"]]
print("\nSample of wines from Italy:")
print(Italy.head(2))

us_spain = df[(df["country"] == "US") | (df["country"] == "Spain")]
print("\nSample of wines from US and Spain:")
print(us_spain.head(2))
print("Interpretation: We successfully filtered the dataset to only include wines from the US and Spain.")

df.country.value_counts().iloc[:10].plot(kind = 'bar', figsize = (16, 8), color = "#9370DB")
plt.title('Number of Wine Reviews by Country')
plt.ylabel('Counts')
plt.xlabel('Countries')
plt.show()
print("Interpretation: The bar chart shows that the US has the highest number of wine reviews in this dataset, followed by France and Italy.")

"""US seems to have the highest number of reviews.

### Exercise 2
Make a similar plot as above, only for top 10 varieties of wine.
"""

df.variety.value_counts().iloc[:10].plot(kind = 'bar', figsize = (16, 8),  color = "#9370DB")
plt.title('Varieties of Wine')
plt.ylabel('Counts')
plt.xlabel('Countries')
plt.show()
print("Interpretation: Pinot Noir and Chardonnay are the most frequently reviewed wine varieties in the dataset.")

exp_wines = df.groupby(['variety'])['price'].max().sort_values(ascending = False).to_frame()[:20]

sns.barplot(x = exp_wines['price'], y = exp_wines.index).set(title='The Most Expensive Varieties')
plt.show()
print("Interpretation: The plot highlights the wine varieties with the highest maximum price. Some rare varieties can be extremely expensive.")

"""### Exercise 3
Group some data to show the highest quality varieties of wine. Use *seaborn* library, `barplot()` function, to produce the visualization.

"""

high_qual = df.groupby(['variety'])['points'].max().sort_values(ascending = False).to_frame()[:20]
sns.barplot(x = high_qual['points'], y = high_qual.index)
plt.title('Highest Quality Wine Varieties')
plt.show()
print("Interpretation: These 20 wine varieties all have achieved a perfect or near-perfect score (typically 100 points) at least once.")

good_under25 = df[(df["price"] < 25) & (df["points"] >= 89)]
print(f"\nThere are {len(good_under25)} wines under $25 with a score of 89 or higher.")
print("Interpretation: Filtering for high points (>=89) and low price (<$25) reveals wines that offer the best value for money.")

"""### Exercise 4
Create a visualization plot showing the lowest priced varieties of wine with higher than '89' score points.

"""

s = good_under25.groupby(['variety'])['price'].min().sort_values(ascending = True).to_frame()[:10]
sns.barplot(x = s['price'], y = s.index)
plt.title('Lowest Priced Good Quality Wine Varieties')
plt.show()
print("Interpretation: This plot shows the absolute cheapest varieties you can buy that still maintain a high quality score (>= 89 points).")

subset = df.sample(frac=0.01)
subset.reset_index(inplace = True,drop = True)
subset.shape

model = SentenceTransformer('distilbert-base-uncased')

embeddings = model.encode(subset['description'], convert_to_tensor=True)
embeddings

print(f"\nDimension of one embedding: {len(embeddings[0])}")
print("Example of the first embedding vector:", embeddings[0][:5], "...")
print("Interpretation: The Hugging Face Transformer converts each textual wine description into a 768-dimensional numerical vector capturing its semantic meaning.")

subset['vectors'] = np.array(embeddings).tolist()

subset.head(1)

model_index = nmslib.init(method='hnsw', space='cosinesimil')

"""### 2. Add the embeddings to the index using `addDataPointBatch()` method.

"""

model_index.addDataPointBatch(embeddings)

"""### 3. Create the index with the data points using `createIndex method()`.

Postprocessing is set to 2 means the maximum level of postprocessing.

"""

model_index.createIndex({'post': 2})

def find_best_wine(data, q_input):

    if data is not None and q_input is not None:
        subset = data.copy()
        query = model.encode([q_input], convert_to_tensor=True)
        ids, distances = model_index.knnQuery(query, k=20)

    best_fits = []
    for i, j in zip(ids, distances):

          best_fits.append({'country':subset.country.values[i]
                        , 'winery' : subset.winery.values[i]
                        , 'title' : subset.title.values[i]
                        , 'variety': subset.variety.values[i]
                        , 'description': subset.description.values[i]
                        , 'price': subset.price.values[i]
                        , 'points': subset.points.values[i]
                        , 'distance': j
                       })
    return pd.DataFrame(best_fits)

most_similar=find_best_wine(subset, "dry and fruity")

print("\nTop 3 matches for 'dry and fruity':")
for i in range(0,3):
    print(most_similar['description'][i][0:-1])
    print("distance:",most_similar['distance'][i])
print("Interpretation: The NLP model successfully found wines whose descriptions semantically match 'dry and fruity'. A smaller distance indicates a closer semantic match in the vector space.")

"""### Exercise 5

In this Exercise, find your best bottle of wine using "high acidity taste tart and zesty" as a descriptor input. Print the descriptions together with their 'distance' parameters. Are they similar to the original input?
"""

exe5 = find_best_wine(subset, "high acidity taste tart and zesty").head(3)

print("\nTop 3 matches for 'high acidity taste tart and zesty':")
for i in range(0,3):
    print(exe5['description'][i][0:-1])
    print("distance:", exe5['distance'][i])
print("Interpretation: By using natural language, we retrieved wines described with words like 'sour', 'harsh', and 'rough', which align perfectly with the target flavor profile of tart and high acidity.")

tsne = TSNE(n_components=2, random_state=42)
tsne_results = tsne.fit_transform(np.array(subset['vectors'].to_list()))
subset['tsnemodel'] = tsne_results.tolist()

plt.figure(figsize=(12, 8))
plt.scatter([vec[0] for vec in subset['tsnemodel']], [vec[1] for vec in subset['tsnemodel']], alpha=0.7)
plt.title('Wine Explorer t-SNE Visualization')
plt.xlabel('t-SNE Dimension 1')
plt.ylabel('t-SNE Dimension 2')
plt.show()
print("Interpretation: The t-SNE plot reduces the complex 768-dimensional embeddings down to 2 dimensions. Each point is a wine, and wines that are clustered closer together have more semantically similar descriptions.")
